# only tagged build/deploy
if: tag IS present

sudo: required
language: node_js
node_js:
  - lts/*

env:
  global:
    # WEB_EXT_API_KEY
    # WEB_EXT_API_SECRET
    - SOURCE=dist/chrome/bundle.zip
    - EXTENSION_ID=pinjkilghdfhnkibhcangnpmcpdpmehk
    - CLIENT_ID=$WS_CLIENT_ID
    - CLIENT_SECRET=$WS_CLIENT_SECRET
    - REFRESH_TOKEN=$WS_REFRESH_TOKEN

before_script:
  - npm i
  - npm run bundle

script:
  - npx --no-install webstore upload --source $SOURCE --extension-id $EXTENSION_ID --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token $REFRESH_TOKEN --auto-publish
